### ISSUE TITLE
RingLogger ran into an issue persisting the log: erofs

### ISSUE THREAD

**Issue by FlorianGerhardt** [nerves-project/ring_logger#123]
### Environment

Raspberry Pi CM4
elixir:  1.14.3
nerves_bootstrap: 1.11.4
:nerves, 1.10.2
:nerves_system_rpi4 1.22.2
:ring_logger 0.10.1

### Current behavior

I'm trying out the persist option via config:
```
config :logger, RingLogger,
  buffers: %{
    errors: %{
      levels: [:error, :warning],
      max_size: 1024
    }
  },
  persist_path: "./production.log",
  persist_seconds: 600
```
and I get in the logs:
`22:18:17.084 [warn] RingLogger ran into an issue persisting the log: erofs` and no logfile has been created.

### Expected behavior
No error and created log file. Do I need to create the logfile manually?

**Comment by jjcarstens** [comment]
Thanks @FlorianGerhardt!

The issue here is the `persist_path` is evaluated at runtime and you have used a relative path which will most likely expand to where this config is stored. Thats somewhere in `/srv/erlang/...` which is part of the RO filesystem.

You need to use an absolute path to a writable partition. So something like `/data/ring_logger/production.log` should work

**Comment by FlorianGerhardt** [comment]
Thanks for the explanation! Maybe it makes sense to put it in the Readme or update the example in the Readme?
