### ISSUE TITLE
Add per module levels

### ISSUE THREAD

**Issue by michaelkschmidt** [nerves-project/ring_logger#5]
The global ":debug" level can get very chatty.  It would be nice to configure per-module levels
```elixir
configure :logger, RingLogger,
   module_levels: %{
      Nerves.Network.Udhcpc => :debug,
      Nerves.Network.Config => :warn,
      Nerves.Network.DHCPManager => :warn,
      Nerves.Network.IFSupervisor => :warn,
   }
```
or
```elixir
iex>  RingLogger.level(Nerves.Network.Udhcpc, :error)
```

Would you like a PR for this?  @adkron wrote such a backend a while back, but it was never open-sourced.  It would be great if we could add it to RingLogger for obvious reasons 

The only caveot with implementing on the backend is that you cannot make modules "more verbose", only less.  The global level filters things at the Log function call.

**Comment by fhunleth** [comment]
I'm +1 on such a feature. Thanks for suggesting it!

I'd like a catch-all so that I can specify that messages coming from any unlisted place is filtered at a given log level. This is to say things like everything is at the `:error` level except for this one module.

The part that's foggy in my mind right now is whether we want to apply the filter before the messages are recorded to the log or when they're queried from the log. I'm leaning on afterwards, since then if you're polling the log via `RingLogger.tail`, you can remove the filter if something interesting happened.

**Comment by michaelkschmidt** [comment]
At first I thought the global level would be the catch-all, but I think I see the usefulness in having it as an option.  Something like 
```
%{ :_ => :error }
```
(I'm open for suggestions)

I think you are right--the filtering should be done when the message is pulled from the ring

**Comment by fhunleth** [comment]
@michaelkschmidt I just ran into a need for this feature again.
